/* tslint:disable */
/* eslint-disable */
/**
 * LazyBlog API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TagResponse } from './TagResponse';
import {
    TagResponseFromJSON,
    TagResponseFromJSONTyped,
    TagResponseToJSON,
} from './TagResponse';
import type { UserResponse } from './UserResponse';
import {
    UserResponseFromJSON,
    UserResponseFromJSONTyped,
    UserResponseToJSON,
} from './UserResponse';
import type { VoteDirection } from './VoteDirection';
import {
    VoteDirectionFromJSON,
    VoteDirectionFromJSONTyped,
    VoteDirectionToJSON,
} from './VoteDirection';

/**
 * 
 * @export
 * @interface PublishedPostResponse
 */
export interface PublishedPostResponse {
    /**
     * 
     * @type {string}
     * @memberof PublishedPostResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PublishedPostResponse
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof PublishedPostResponse
     */
    summary?: string;
    /**
     * 
     * @type {string}
     * @memberof PublishedPostResponse
     */
    slug?: string;
    /**
     * 
     * @type {UserResponse}
     * @memberof PublishedPostResponse
     */
    author?: UserResponse;
    /**
     * 
     * @type {number}
     * @memberof PublishedPostResponse
     */
    views?: number;
    /**
     * 
     * @type {number}
     * @memberof PublishedPostResponse
     */
    comments?: number;
    /**
     * 
     * @type {number}
     * @memberof PublishedPostResponse
     */
    rating?: number;
    /**
     * 
     * @type {VoteDirection}
     * @memberof PublishedPostResponse
     */
    voteDirection?: VoteDirection;
    /**
     * 
     * @type {string}
     * @memberof PublishedPostResponse
     */
    coverUrl?: string;
    /**
     * 
     * @type {Array<TagResponse>}
     * @memberof PublishedPostResponse
     */
    tags?: Array<TagResponse>;
    /**
     * 
     * @type {Date}
     * @memberof PublishedPostResponse
     */
    createdAtUtc?: Date;
}

/**
 * Check if a given object implements the PublishedPostResponse interface.
 */
export function instanceOfPublishedPostResponse(value: object): boolean {
    return true;
}

export function PublishedPostResponseFromJSON(json: any): PublishedPostResponse {
    return PublishedPostResponseFromJSONTyped(json, false);
}

export function PublishedPostResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublishedPostResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'author': json['author'] == null ? undefined : UserResponseFromJSON(json['author']),
        'views': json['views'] == null ? undefined : json['views'],
        'comments': json['comments'] == null ? undefined : json['comments'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'voteDirection': json['voteDirection'] == null ? undefined : VoteDirectionFromJSON(json['voteDirection']),
        'coverUrl': json['coverUrl'] == null ? undefined : json['coverUrl'],
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(TagResponseFromJSON)),
        'createdAtUtc': json['createdAtUtc'] == null ? undefined : (new Date(json['createdAtUtc'])),
    };
}

export function PublishedPostResponseToJSON(value?: PublishedPostResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'title': value['title'],
        'summary': value['summary'],
        'slug': value['slug'],
        'author': UserResponseToJSON(value['author']),
        'views': value['views'],
        'comments': value['comments'],
        'rating': value['rating'],
        'voteDirection': VoteDirectionToJSON(value['voteDirection']),
        'coverUrl': value['coverUrl'],
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(TagResponseToJSON)),
        'createdAtUtc': value['createdAtUtc'] == null ? undefined : ((value['createdAtUtc']).toISOString()),
    };
}

